/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visoes;

import Controladores.ControladorTelaLogin;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private final ControladorTelaLogin controlador;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        
        controlador = new ControladorTelaLogin(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrar = new javax.swing.JButton();
        jPasswordFieldPermissao = new javax.swing.JPasswordField();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelPermissao = new javax.swing.JLabel();
        jButtonLogin1 = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();
        jLabelLogin1 = new javax.swing.JLabel();
        jPasswordFieldSenha1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCadastrar.setText("Cadastrar ");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 90, -1));
        getContentPane().add(jPasswordFieldPermissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 230, -1));
        getContentPane().add(jTextFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 230, -1));

        jLabelSenha.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitulo.setText("Cenaflix");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 180, -1));

        jLabelPermissao.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelPermissao.setText("Permissão:");
        getContentPane().add(jLabelPermissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jButtonLogin1.setText("Login");
        jButtonLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 90, -1));
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 510));

        jLabelLogin1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelLogin1.setText("Login:");
        getContentPane().add(jLabelLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));
        getContentPane().add(jPasswordFieldSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
       controlador.inserirUsuarioNobanco();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin1ActionPerformed
      controlador.fazerLogin();
    }//GEN-LAST:event_jButtonLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    public JPasswordField getjPasswordFieldPermissao() {
        return jPasswordFieldPermissao;
    }

    public void setjPasswordFieldPermissao(JPasswordField jPasswordFieldPermissao) {
        this.jPasswordFieldPermissao = jPasswordFieldPermissao;
    }

    public JPasswordField getjPasswordFieldSenha1() {
        return jPasswordFieldSenha1;
    }

    public void setjPasswordFieldSenha1(JPasswordField jPasswordFieldSenha1) {
        this.jPasswordFieldSenha1 = jPasswordFieldSenha1;
    }

    public JTextField getjTextFieldLogin() {
        return jTextFieldLogin;
    }

    public void setjTextFieldLogin(JTextField jTextFieldLogin) {
        this.jTextFieldLogin = jTextFieldLogin;
    }

    public JButton getjButtonCadastrar() {
        return jButtonCadastrar;
    }

    public void setjButtonCadastrar(JButton jButtonCadastrar) {
        this.jButtonCadastrar = jButtonCadastrar;
    }

    public JLabel getjLabelPermissao() {
        return jLabelPermissao;
    }

    public void setjLabelPermissao(JLabel jLabelPermissao) {
        this.jLabelPermissao = jLabelPermissao;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonLogin1;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLogin1;
    private javax.swing.JLabel jLabelPermissao;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPasswordField jPasswordFieldPermissao;
    private javax.swing.JPasswordField jPasswordFieldSenha1;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
