/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visoes;

import Controladores.ControladorTelaCadastrar;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo
 */
public class TelaCadastrar extends javax.swing.JFrame {
    
    private final ControladorTelaCadastrar controlador;

    /**
     * Creates new form TelaCadastrar
     */
    public TelaCadastrar() {
        initComponents();
        
        controlador = new ControladorTelaCadastrar(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextFieldDuracao = new javax.swing.JFormattedTextField();
        jTextFieldUrlRepositorio = new javax.swing.JTextField();
        jLabelUrlRepositorio = new javax.swing.JLabel();
        jLabelSubtitulo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelProdutor = new javax.swing.JLabel();
        jLabelNomeEpisodio = new javax.swing.JLabel();
        jLabelNepisodio = new javax.swing.JLabel();
        jLabelDuracao = new javax.swing.JLabel();
        jTextFieldProdutor = new javax.swing.JTextField();
        jTextFieldNomeEpisodio = new javax.swing.JTextField();
        jTextFieldNumeroEpisodio = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonVerListagem = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try {
            jFormattedTextFieldDuracao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldDuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 180, 30));
        getContentPane().add(jTextFieldUrlRepositorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 180, -1));

        jLabelUrlRepositorio.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelUrlRepositorio.setText("Url do repositório");
        getContentPane().add(jLabelUrlRepositorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        jLabelSubtitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelSubtitulo.setText("Cadastrar Podcast");
        getContentPane().add(jLabelSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 230, -1));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitulo.setText("Cenaflix");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 140, 30));

        jLabelProdutor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelProdutor.setText("Produtor");
        getContentPane().add(jLabelProdutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jLabelNomeEpisodio.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelNomeEpisodio.setText("Nome do episódio");
        getContentPane().add(jLabelNomeEpisodio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        jLabelNepisodio.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelNepisodio.setText("Nº do episódio");
        getContentPane().add(jLabelNepisodio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jLabelDuracao.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelDuracao.setText("Duração");
        getContentPane().add(jLabelDuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));
        getContentPane().add(jTextFieldProdutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 180, -1));
        getContentPane().add(jTextFieldNomeEpisodio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 180, -1));
        getContentPane().add(jTextFieldNumeroEpisodio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 180, -1));

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        jButtonVerListagem.setText("Ver listagem");
        jButtonVerListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerListagemActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerListagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
       controlador.inserirPodcastNoBanco();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonVerListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerListagemActionPerformed
       controlador.irTelaListagem();
    }//GEN-LAST:event_jButtonVerListagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrar().setVisible(true);
            }
        });
    }

    public JFormattedTextField getjFormattedTextFieldDuracao() {
        return jFormattedTextFieldDuracao;
    }

    public void setjFormattedTextFieldDuracao(JFormattedTextField jFormattedTextFieldDuracao) {
        this.jFormattedTextFieldDuracao = jFormattedTextFieldDuracao;
    }

    public JTextField getjTextFieldNomeEpisodio() {
        return jTextFieldNomeEpisodio;
    }

    public void setjTextFieldNomeEpisodio(JTextField jTextFieldNomeEpisodio) {
        this.jTextFieldNomeEpisodio = jTextFieldNomeEpisodio;
    }

    public JTextField getjTextFieldNumeroEpisodio() {
        return jTextFieldNumeroEpisodio;
    }

    public void setjTextFieldNumeroEpisodio(JTextField jTextFieldNumeroEpisodio) {
        this.jTextFieldNumeroEpisodio = jTextFieldNumeroEpisodio;
    }

    public JTextField getjTextFieldProdutor() {
        return jTextFieldProdutor;
    }

    public void setjTextFieldProdutor(JTextField jTextFieldProdutor) {
        this.jTextFieldProdutor = jTextFieldProdutor;
    }

    public JTextField getjTextFieldUrlRepositorio() {
        return jTextFieldUrlRepositorio;
    }

    public void setjTextFieldUrlRepositorio(JTextField jTextFieldUrlRepositorio) {
        this.jTextFieldUrlRepositorio = jTextFieldUrlRepositorio;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonVerListagem;
    private javax.swing.JFormattedTextField jFormattedTextFieldDuracao;
    private javax.swing.JLabel jLabelDuracao;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNepisodio;
    private javax.swing.JLabel jLabelNomeEpisodio;
    private javax.swing.JLabel jLabelProdutor;
    private javax.swing.JLabel jLabelSubtitulo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUrlRepositorio;
    private javax.swing.JTextField jTextFieldNomeEpisodio;
    private javax.swing.JTextField jTextFieldNumeroEpisodio;
    private javax.swing.JTextField jTextFieldProdutor;
    private javax.swing.JTextField jTextFieldUrlRepositorio;
    // End of variables declaration//GEN-END:variables
}
